configfile: "/data/evaluation/MPP/stochastic_MPP_Felix/tools/MPP/workflow/lumpings.yml"

# TODO:
# - good way to load lumpings.yml
# - source in config file required? Probably yes, because of all the file that are loaded within python.

import os


def get_d(wildcards):
  return config[wildcards.lumping]["kernel similarity"]

def get_g(wildcards):
  return config[wildcards.lumping]["feature kernel"]

def get_top_file(wildcards):
  configfile: "data/" + wildcards.system + "/input/config.yml"
  return config["source"] + config["topology file"]

def get_xtc_file(wildcards):
  configfile: "data/" + wildcards.system + "/input/config.yml"
  return config["source"] + config["xtc file"]

def get_contact_index_file(wildcards):
  configfile: "data/" + wildcards.system + "/input/config.yml"
  if "contact index file" in config:
    return os.path.join(config["source"], config["contact index file"])
  else:
    return "none"

def get_xtc_stride(wildcards):
  configfile: "data/" + wildcards.system + "/input/config.yml"
  if "xtc stride" in config:
    return int(config["xtc stride"])
  else:
    return 1

def get_mem_mb(wildcards):
  configfile: "data/" + wildcards.system + "/input/config.yml"
  return os.path.getsize(os.path.join(config["source"], config["xtc file"])) / 1e6 + 500

rule gen_Z:
  input:
    "data/{system}/input/config.yml",
  output:
    "data/{system}/results/{lumping}/Z.npy"
  params:
    d=get_d,
    g=get_g
  conda:
    "mpp"
  cache: True
  shell:
    "python -m MPP.run {input} {params.d} {params.g} -Z {output}"

rule plot:
  input:
    config="data/{system}/input/config.yml",
    z="data/{system}/results/{lumping}/Z.npy"
  output:
    "data/{system}/results/{lumping}/{plot}.{ext}"
  wildcard_constraints:
    ext="pdf|png|txt"
  params:
    d=get_d,
    g=get_g
  conda:
    "mpp"
    # "mpp.yml"
  shell:
    "python -m MPP.run {input.config} {params.d} {params.g} -Z {input.z} -p {wildcards.plot} -o {output}"

rule rmsd_CA:
  input:
    config="data/{system}/input/config.yml",
    z="data/{system}/results/{lumping}/Z.npy"
  output:
    npy="data/{system}/results/{lumping}/rmsd_CA.npy",
    ndx="data/{system}/results/{lumping}/rmsd_CA_mean_frames.ndx"
  params:
    d=get_d,
    g=get_g
  resources:
    mem_mb=get_mem_mb
  conda:
    "mpp"
    # "mpp.yml"
  shell:
    "python -m MPP.run {input.config} {params.d} {params.g} -Z {input.z} --rmsd {output.npy}"

rule rmsd_feature:
  input:
    config="data/{system}/input/config.yml",
    z="data/{system}/results/{lumping}/Z.npy"
  output:
    npy="data/{system}/results/{lumping}/rmsd_feature.npy",
    ndx="data/{system}/results/{lumping}/rmsd_feature_mean_frames.ndx"
  params:
    d=get_d,
    g=get_g
  resources:
    mem_mb=get_mem_mb
  conda:
    "mpp"
    # "mpp.yml"
  shell:
    "python -m MPP.run {input.config} {params.d} {params.g} -Z {input.z} --rmsd {output.npy} --rmsd-feature feature"

checkpoint draw_random:
  input:
    config="data/{system}/input/config.yml",
    z="data/{system}/results/{lumping}/Z.npy"
  output:
    macrostates=directory("data/{system}/results/{lumping}/random_frames/")
  params:
    d=get_d,
    g=get_g,
    n=20
  conda:
    "mpp"
    # "mpp.yml"
  shell:
    "python -m MPP.run {input.config} {params.d} {params.g} -Z {input.z} -r {params.n} -o {output}"

def aggregate_input(wildcards):
    checkpoint_output = checkpoints.draw_random.get(**wildcards).output[0]
    return expand("data/{system}/results/{lumping}/random_pngs/{macrostate}.png",
           system=wildcards.system,
           lumping=wildcards.lumping,
           macrostate=glob_wildcards(os.path.join(checkpoint_output, "{macrostate}.ndx")).macrostate)

def aggregate_input_pdb(wildcards):
    checkpoint_output = checkpoints.draw_random.get(**wildcards).output[0]
    return expand("data/{system}/results/{lumping}/random_pdbs/{macrostate}.pdb",
           system=wildcards.system,
           lumping=wildcards.lumping,
           macrostate=glob_wildcards(os.path.join(checkpoint_output, "{macrostate}.ndx")).macrostate)

rule aggregate:
  input:
    aggregate_input
  output:
    "data/{system}/results/{lumping}/macrostates.txt"
  shell:
    "echo {input} > {output}"

rule aggregate_pdb:
  input:
    aggregate_input_pdb
  output:
    "data/{system}/results/{lumping}/macrostates_pdb.txt"
  shell:
    "echo {input} > {output}"


rule get_least_moving_residues:
  input:
    config="data/{system}/input/config.yml",
    z="data/{system}/results/{lumping}/Z.npy"
  output:
    "data/{system}/results/{lumping}/least_moving_residues.ndx"
  params:
    d=get_d,
    g=get_g,
    ndx_file=get_contact_index_file,
  conda:
    "mpp"
  shell:
    "python -m MPP.run {input.config} {params.d} {params.g} -Z {input.z} -o {output} --get-least-moving-residues {params.ndx_file}"

# TODO:
# Mind the xtc stride / --skip not working; rewrite of .ndx required
rule get_random_pdb_frames:
  input:
    "data/{system}/results/{lumping}/random_frames/{macrostate}.ndx"
  output:
    "data/{system}/results/{lumping}/random_pdbs/{macrostate}.pdb"
  params:
    top=get_top_file,
    xtc=get_xtc_file,
  shell:
    """mkdir -p random_pdbs
gmx trjconv -s {params.top} -f {params.xtc} -o {output} -fr {input} <<eof
0
eof"""

rule get_mean_frames_pdb_CA:
  input:
    "data/{system}/results/{lumping}/rmsd_CA_mean_frames.ndx"
  output:
    "data/{system}/results/{lumping}/mean_frames_CA.pdb"
  params:
    top=get_top_file,
    xtc=get_xtc_file,
  shell:
    """mkdir -p random_pdbs
gmx trjconv -s {params.top} -f {params.xtc} -o {output} -fr {input} <<eof
0
eof"""

rule get_mean_frames_pdb_feature:
  input:
    "data/{system}/results/{lumping}/rmsd_feature_mean_frames.ndx"
  output:
    "data/{system}/results/{lumping}/mean_frames_feature.pdb"
  params:
    top=get_top_file,
    xtc=get_xtc_file,
  shell:
    """mkdir -p random_pdbs
gmx trjconv -s {params.top} -f {params.xtc} -o {output} -fr {input} <<eof
0
eof"""

rule render_pdb_files:
  input:
    pdb="data/{system}/results/{lumping}/random_pdbs/{macrostate}.pdb",
    ndx="data/{system}/results/{lumping}/least_moving_residues.ndx",
  output:
    "data/{system}/results/{lumping}/random_pngs/{macrostate}.png"
  conda:
    "pymol"
  params:
    ndx_file=get_contact_index_file,
  shell:
    "pymol -cq workflow/render_random_structures.py -- {input.pdb} {output} {input.ndx}"


checkpoint draw_cluster_in_states:
  input:
    config="data/{system}/input/config.yml",
    frames="data/{system}/results/{lumping}/mean_frames_{rmsd_feature}.pdb"
  output:
    directory("data/{system}/results/{lumping}/mean_frames_{rmsd_feature}_{clusters}/")
  conda:
    "pymol"
  shell:
    "workflow/create_cluster_pml.py {output} {input.config} {input.frames} {wildcards.clusters}"

def aggregate_input_draw_cluster(wildcards):
    checkpoint_output = checkpoints.draw_cluster_in_states.get(**wildcards).output[0]
    return expand("data/{system}/results/{lumping}/mean_frames_{rmsd_feature}/{macrostate}.png",
           system=wildcards.system,
           lumping=wildcards.lumping,
           macrostate=glob_wildcards(os.path.join(checkpoint_output, "{macrostate}.png")).macrostate)

rule aggregate_draw_cluster:
  input:
    aggregate_input_draw_cluster
  output:
    "data/{system}/results/{lumping}/rmsd_mean_{rmsd_feature}_{clusters}.txt"
  shell:
    "echo {input} > {output}"



rule report:
  input:
    "data/{system}/results/{lumping}/sankey.pdf",
    "data/{system}/results/{lumping}/dendrogram.pdf",
    "data/{system}/results/{lumping}/ck_test.pdf",
    "data/{system}/results/{lumping}/timescales.pdf",
    "data/{system}/results/{lumping}/contacts.pdf",
    "data/{system}/results/{lumping}/macrotraj.pdf",
  output:
    "data/{system}/results/{lumping}/report.tex",
  conda:
    "mpp"
  shell:
    "python workflow/report.py {wildcards.system} {wildcards.lumping}"

rule report_rmsd:
  input:
    "data/{system}/results/{lumping}/sankey.pdf",
    "data/{system}/results/{lumping}/dendrogram.pdf",
    "data/{system}/results/{lumping}/ck_test.pdf",
    "data/{system}/results/{lumping}/timescales.pdf",
    "data/{system}/results/{lumping}/contacts.pdf",
    "data/{system}/results/{lumping}/macrotraj.pdf",
    "data/{system}/results/{lumping}/rmsd.pdf",
  output:
    "data/{system}/results/{lumping}/report_rmsd.tex",
  conda:
    "mpp"
  shell:
    "python workflow/report.py {wildcards.system} {wildcards.lumping} -r"
