source: example/sample_system/input

microstate_trajectory: traj
multi_feature_trajectory: feature_traj
contact_threshold: null
# cluster_file: clusters
# contact_index_file: contacts.ndx
# limits: null
#
# topology_file: structure.pdb
# xtc_file: trajectory.xtc
# helices: helices

frame_length: 0.2 # in ns / frame
lagtime: 20 # in frames
pop_thr: 0.15
q_min: 0.5

# PyMol rendering
# view: view
# width: 500
# height: 500
